# Copyright (c) 2026, TatvaCare and Contributors
# See license.txt
"""Lock 1 — the five listing declarations are OURS, they live here, and they are exactly the fixture.

`default_list_data()` is the one brain of a listing page: it says which columns exist, what each is
called, how wide it is and in what order, plus the `rows` the column picker may offer. Three consumers
already resolve through it and all three reach it the same way, through
`frappe.model.document.get_controller()` — the list payload (`crm/api/doc.py:301,338`), what a saved
view is seeded from (`crm_view_settings.py:174,195`) and the four pickers
(`tatva_connect/api/task_lenses.py:45`).

So this test asks the question those consumers ask, and nothing narrower: it calls `get_controller(dt)`
and compares its answer to a committed fixture, dict for dict, list order included. That single
assertion covers both halves of the rehoming at once — the declaration must be reachable (the
`override_doctype_class` entry is wired) and it must be intact (nothing was tidied in transit).

The fixture was generated by reading the fork's Python with `ast`, before the fork was returned to
upstream. It is the contract, not a snapshot: when a label deliberately changes, the fixture edit and
the code edit sit side by side in the same diff, which is what makes a rename reviewable instead of
silent.

Run:
    bench --site dev.localhost run-tests --app tatva_connect \\
        --module tatva_connect.tests.list_engine.test_column_declaration_rehome
"""

import json
import pathlib

import frappe
from frappe.model.document import get_controller
from frappe.tests.utils import FrappeTestCase

FIXTURE = (
	pathlib.Path(frappe.get_app_path("tatva_connect"))
	/ "tests"
	/ "list_engine"
	/ "fixtures"
	/ "column_declarations_pre_rehome.json"
)

# Lock 3 — the lead reference's ONE key and ONE label — lives in tests/architecture/test_listing_declaration_home.py.
LEAD_REFERENCE_KEY = "reference_docname"


def _declared(doctype):
	return get_controller(doctype).default_list_data()


class TestColumnDeclarationRehome(FrappeTestCase):
	@classmethod
	def setUpClass(cls):
		super().setUpClass()
		cls.expected = json.loads(FIXTURE.read_text())

	def test_every_declaration_matches_the_fixture_exactly(self):
		"""One assertion per doctype, so a failure names which list moved and how."""
		for doctype, expected in self.expected.items():
			with self.subTest(doctype=doctype):
				self.assertEqual(_declared(doctype), expected)

	def test_the_declaration_resolves_through_our_class(self):
		"""The hook is the seam: if `get_controller` still answers with the fork's class, nothing moved."""
		for doctype in self.expected:
			with self.subTest(doctype=doctype):
				controller = get_controller(doctype)
				self.assertEqual(controller.__module__, "tatva_connect.list_engine.columns")

	def test_a_note_carries_its_own_id_and_the_lead(self):
		"""A2 — FCRM Note answered with no columns at all, so the browser kept a private copy."""
		columns = _declared("FCRM Note")["columns"]
		self.assertEqual(next(c["label"] for c in columns), "Note ID")
		self.assertEqual(columns[0]["key"], "name")
		self.assertIn(LEAD_REFERENCE_KEY, [c["key"] for c in columns])

	def test_a_lead_leads_with_its_name_not_its_id(self):
		"""A3 — `Full Name` is the first column; `Lead ID` stays offerable through `rows`."""
		declaration = _declared("CRM Lead")
		self.assertEqual(declaration["columns"][0]["key"], "lead_name")
		self.assertNotIn("name", [c["key"] for c in declaration["columns"]])
		self.assertIn("name", declaration["rows"])
