"""Our helpdesk layer: the doctypes it touches, named once, so no module declares one of them twice."""
TICKET = "HD Ticket"
SUB_TYPE = "HD Ticket Sub Type"
TRANSITION = "HD Ticket Transition"
SOURCE = "HD Ticket Source"
ROUTING = "HD Ticket Routing"
